# Generated by Django 5.0 on 2025-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/covers/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
