# Generated by Django 5.0 on 2025-08-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_cover_project_tech_stack_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
