# Generated by Django 5.0 on 2025-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tag_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на демо"),
        ),
        migrations.AddField(
            model_name="project",
            name="repo_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на репозиторий"),
        ),
    ]
